apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    # Bootstrap value. The address-pool-configurator Job replaces the network
    # prefix at runtime using the CRC node IP.
    - 192.168.126.200-192.168.126.250
  autoAssign: true
