apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  addresses:
    - 192.168.130.200-192.168.130.250   # EXEMPLO – ajuste para sua rede L2
  autoAssign: true
