apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  name: metallb-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic